In [2]:
a = [1,2,3]

In [3]:
b = 10

In [4]:
a + b

TypeError: can only concatenate list (not "int") to list

In [7]:
1.0/a

TypeError: unsupported operand type(s) for /: 'float' and 'list'

In [8]:
import numpy as np

In [9]:
x = np.float(1)

In [10]:
x

1.0

In [11]:
x = np.int_(2)

In [12]:
x

2

In [13]:
x.dtype

dtype('int64')

In [14]:
x = np.arange(5,dtype=float)

In [15]:
x

array([ 0.,  1.,  2.,  3.,  4.])

In [16]:
x.dtype

dtype('float64')

In [17]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [19]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [20]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [22]:
np.ones((2,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [23]:
x = np.arange(10)

In [24]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
x.shape = (2,5)

In [29]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
x[1,2]

7

In [31]:
x[1,2] = 87

In [32]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 87,  8,  9]])

In [34]:
x = np.array([[1,2],[1,3]])

In [35]:
x

array([[1, 2],
       [1, 3]])

In [36]:
x = np.array([[1,2],[1,3],[2+1j,1+0j]])

In [37]:
x

array([[ 1.+0.j,  2.+0.j],
       [ 1.+0.j,  3.+0.j],
       [ 2.+1.j,  1.+0.j]])

In [38]:
a = [1,2,3]

In [39]:
a

[1, 2, 3]

In [40]:
a = np.asarray(a)

In [41]:
a

array([1, 2, 3])

In [45]:
x = np.array([[1+1j,2+0j],[2+3j,4+1j],(1+0j,2-3j)])

In [46]:
x

array([[ 1.+1.j,  2.+0.j],
       [ 2.+3.j,  4.+1.j],
       [ 1.+0.j,  2.-3.j]])

In [156]:
x.dtype

dtype('float64')

In [161]:
x = np.array([
    [1,2.0,4],
    [0.5,0.5],
    (1+2j,3.),
    ('a','b')
])

In [162]:
x

array([list([1, 2.0, 4]), list([0.5, 0.5]), ((1+2j), 3.0), ('a', 'b')], dtype=object)

In [163]:
x.dtype

dtype('O')

In [165]:
x[3][0]

'a'

In [166]:
np.linspace(1., 4.,5)

array([ 1.  ,  1.75,  2.5 ,  3.25,  4.  ])

In [167]:
np.random.random((2,3))

array([[ 0.61083585,  0.86449727,  0.6464337 ],
       [ 0.21950491,  0.29389767,  0.20771857]])

In [168]:
np.random.randint(3,size=(1,3))

array([[0, 2, 0]])

In [169]:
x

array([list([1, 2.0, 4]), list([0.5, 0.5]), ((1+2j), 3.0), ('a', 'b')], dtype=object)

In [170]:
print(x)

[list([1, 2.0, 4]) list([0.5, 0.5]) ((1+2j), 3.0) ('a', 'b')]


In [171]:
x = np.arange(25).reshape(5,5)

In [172]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [173]:
np.arange(64).reshape(4,4,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [174]:
x = np.arange(10)

In [175]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [176]:
x[-9]

1

In [177]:
x[-10]

0

In [178]:
x[-1]

9

In [179]:
x.shape = (2,5)

In [180]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [181]:
x[1,-2]

8

In [182]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [183]:
x = 10 + x

In [184]:
1/x

array([[ 0.1       ,  0.09090909,  0.08333333,  0.07692308,  0.07142857],
       [ 0.06666667,  0.0625    ,  0.05882353,  0.05555556,  0.05263158]])

In [185]:
x[1,1:4]

array([16, 17, 18])

In [186]:
x

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [187]:
x + 1

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [188]:
x

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [189]:
x = np.arange(35).reshape(5,7)

In [190]:
x

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [191]:
x[1:7:2]

array([[ 7,  8,  9, 10, 11, 12, 13],
       [21, 22, 23, 24, 25, 26, 27]])

In [192]:
x[:,5]

array([ 5, 12, 19, 26, 33])

In [193]:
x[1:3,3]

array([10, 17])

In [194]:
x[2:4,1:3]

array([[15, 16],
       [22, 23]])

In [195]:
x[0,:]

array([0, 1, 2, 3, 4, 5, 6])

In [196]:
x

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [197]:
x[1:5:2,::3]

array([[ 7, 10, 13],
       [21, 24, 27]])

In [198]:
x[1::3,3::3]

array([[10, 13],
       [31, 34]])

In [199]:
a =np.array([1,2,3])

In [200]:
b = np.array([4,5,6])

In [201]:
a+b

array([5, 7, 9])

In [202]:
a-b

array([-3, -3, -3])

In [203]:
a

array([1, 2, 3])

In [204]:
b

array([4, 5, 6])

In [205]:
a*b

array([ 4, 10, 18])

In [206]:
a

array([1, 2, 3])

In [207]:
b

array([4, 5, 6])

In [208]:
a = np.zeros((2,2))

In [209]:
a

array([[ 0.,  0.],
       [ 0.,  0.]])

In [210]:
a[0,0] = 1

In [211]:
a[1,1] = 1

In [212]:
a

array([[ 1.,  0.],
       [ 0.,  1.]])

In [213]:
x = np.eye(2,2)

In [214]:
x

array([[ 1.,  0.],
       [ 0.,  1.]])

In [215]:
b = np.arange(4).reshape(2,2)

In [216]:
b

array([[0, 1],
       [2, 3]])

In [217]:
a

array([[ 1.,  0.],
       [ 0.,  1.]])

In [218]:
b

array([[0, 1],
       [2, 3]])

In [219]:
a*b

array([[ 0.,  0.],
       [ 0.,  3.]])

In [220]:
x = np.dot(a,b)

In [221]:
x

array([[ 0.,  1.],
       [ 2.,  3.]])

In [222]:
a = np.arange(4)

In [223]:
a

array([0, 1, 2, 3])

In [224]:
a>3

array([False, False, False, False], dtype=bool)

In [225]:
a>2

array([False, False, False,  True], dtype=bool)

In [226]:
10 * np.sin(a)

array([ 0.        ,  8.41470985,  9.09297427,  1.41120008])

In [227]:
x = np.random.random((4,5))

In [228]:
x

array([[ 0.80648122,  0.57410223,  0.18970231,  0.09065982,  0.3712386 ],
       [ 0.73432223,  0.43146957,  0.64563271,  0.61180797,  0.74788459],
       [ 0.70818358,  0.91272556,  0.34178995,  0.88921926,  0.28327573],
       [ 0.79596433,  0.18461042,  0.29002685,  0.9427531 ,  0.98969164]])

In [229]:
x.sum()

11.541541675056058

In [230]:
x.min()

0.090659820311868589

In [231]:
x.max()

0.98969163691441631

In [232]:
x.min(axis=1)

array([ 0.09065982,  0.43146957,  0.28327573,  0.18461042])

In [233]:
x.min(axis=0)

array([ 0.70818358,  0.18461042,  0.18970231,  0.09065982,  0.28327573])

In [234]:
x

array([[ 0.80648122,  0.57410223,  0.18970231,  0.09065982,  0.3712386 ],
       [ 0.73432223,  0.43146957,  0.64563271,  0.61180797,  0.74788459],
       [ 0.70818358,  0.91272556,  0.34178995,  0.88921926,  0.28327573],
       [ 0.79596433,  0.18461042,  0.29002685,  0.9427531 ,  0.98969164]])

In [235]:
x

array([[ 0.80648122,  0.57410223,  0.18970231,  0.09065982,  0.3712386 ],
       [ 0.73432223,  0.43146957,  0.64563271,  0.61180797,  0.74788459],
       [ 0.70818358,  0.91272556,  0.34178995,  0.88921926,  0.28327573],
       [ 0.79596433,  0.18461042,  0.29002685,  0.9427531 ,  0.98969164]])

In [236]:
x = x.ravel()

In [237]:
x.shape

(20,)

In [238]:
x.shape=(4,5)

In [239]:
x

array([[ 0.80648122,  0.57410223,  0.18970231,  0.09065982,  0.3712386 ],
       [ 0.73432223,  0.43146957,  0.64563271,  0.61180797,  0.74788459],
       [ 0.70818358,  0.91272556,  0.34178995,  0.88921926,  0.28327573],
       [ 0.79596433,  0.18461042,  0.29002685,  0.9427531 ,  0.98969164]])

In [240]:
x.transpose()

array([[ 0.80648122,  0.73432223,  0.70818358,  0.79596433],
       [ 0.57410223,  0.43146957,  0.91272556,  0.18461042],
       [ 0.18970231,  0.64563271,  0.34178995,  0.29002685],
       [ 0.09065982,  0.61180797,  0.88921926,  0.9427531 ],
       [ 0.3712386 ,  0.74788459,  0.28327573,  0.98969164]])