In [2]:
a = [1,2,3]

In [3]:
b = 10

In [4]:
a + b

TypeError: can only concatenate list (not "int") to list

In [7]:
1.0/a

TypeError: unsupported operand type(s) for /: 'float' and 'list'

In [8]:
import numpy as np

In [9]:
x = np.float(1)

In [10]:
x

1.0

In [11]:
x = np.int_(2)

In [12]:
x

2

In [13]:
x.dtype

dtype('int64')

In [14]:
x = np.arange(5,dtype=float)

In [15]:
x

array([ 0.,  1.,  2.,  3.,  4.])

In [16]:
x.dtype

dtype('float64')

In [17]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [19]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [20]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [22]:
np.ones((2,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [23]:
x = np.arange(10)

In [24]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
x.shape = (2,5)

In [29]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
x[1,2]

7

In [31]:
x[1,2] = 87

In [32]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 87,  8,  9]])

In [34]:
x = np.array([[1,2],[1,3]])

In [35]:
x

array([[1, 2],
       [1, 3]])

In [36]:
x = np.array([[1,2],[1,3],[2+1j,1+0j]])

In [37]:
x

array([[ 1.+0.j,  2.+0.j],
       [ 1.+0.j,  3.+0.j],
       [ 2.+1.j,  1.+0.j]])

In [38]:
a = [1,2,3]

In [39]:
a

[1, 2, 3]

In [40]:
a = np.asarray(a)

In [41]:
a

array([1, 2, 3])

In [45]:
x = np.array([[1+1j,2+0j],[2+3j,4+1j],(1+0j,2-3j)])

In [46]:
x

array([[ 1.+1.j,  2.+0.j],
       [ 2.+3.j,  4.+1.j],
       [ 1.+0.j,  2.-3.j]])

In [47]:
x.dtype

dtype('complex128')

In [63]:
x = np.array([
    [1,2.0],
    [0.5,0],
    (1+2j,3.),
    ('a','b')
])

SyntaxError: invalid syntax (<ipython-input-63-0584c0133d64>, line 5)

In [58]:
x

array([['1', '2.0'],
       ['0.5', '0'],
       ['(1+2j)', '3.0'],
       ['a', 'b']],
      dtype='<U64')

In [60]:
x.dtype

dtype('<U64')

In [62]:
x[3,0]

'a'

In [64]:
np.linspace(1., 4.,5)

array([ 1.  ,  1.75,  2.5 ,  3.25,  4.  ])

In [65]:
np.random.random((2,3))

array([[ 0.2931306 ,  0.74727813,  0.83939472],
       [ 0.1993216 ,  0.05648332,  0.34244045]])

In [69]:
np.random.randint(3,size=(1,3))

array([[0, 2, 2]])

In [70]:
x

array([['1', '2.0'],
       ['0.5', '0'],
       ['(1+2j)', '3.0'],
       ['a', 'b']],
      dtype='<U64')

In [71]:
print(x)

[['1' '2.0']
 ['0.5' '0']
 ['(1+2j)' '3.0']
 ['a' 'b']]


In [72]:
x = np.arange(25).reshape(5,5)

In [73]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [74]:
np.arange(64).reshape(4,4,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [75]:
x = np.arange(10)

In [76]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
x[-9]

1

In [78]:
x[-10]

0

In [79]:
x[-1]

9

In [80]:
x.shape = (2,5)

In [81]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [83]:
x[1,-2]

8

In [84]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [88]:
x = 10 + x

In [86]:
1/x

/Users/nayeem/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111]])

In [89]:
x[1,1:4]

array([16, 17, 18])

In [90]:
x

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [91]:
x + 1

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [92]:
x

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [93]:
x = np.arange(35).reshape(5,7)

In [94]:
x

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [96]:
x[1:7:2]

array([[ 7,  8,  9, 10, 11, 12, 13],
       [21, 22, 23, 24, 25, 26, 27]])

In [97]:
x[:,5]

array([ 5, 12, 19, 26, 33])

In [98]:
x[1:3,3]

array([10, 17])

In [99]:
x[2:4,1:3]

array([[15, 16],
       [22, 23]])

In [100]:
x[0,:]

array([0, 1, 2, 3, 4, 5, 6])

In [101]:
x

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [102]:
x[1:5:2,::3]

array([[ 7, 10, 13],
       [21, 24, 27]])

In [103]:
x[1::3,3::3]

array([[10, 13],
       [31, 34]])

In [105]:
a =np.array([1,2,3])

In [106]:
b = np.array([4,5,6])

In [107]:
a+b

array([5, 7, 9])

In [108]:
a-b

array([-3, -3, -3])

In [109]:
a

array([1, 2, 3])

In [110]:
b

array([4, 5, 6])

In [111]:
a*b

array([ 4, 10, 18])

In [112]:
a

array([1, 2, 3])

In [113]:
b

array([4, 5, 6])

In [114]:
a = np.zeros((2,2))

In [115]:
a

array([[ 0.,  0.],
       [ 0.,  0.]])

In [116]:
a[0,0] = 1

In [117]:
a[1,1] = 1

In [118]:
a

array([[ 1.,  0.],
       [ 0.,  1.]])

In [120]:
x = np.eye(2,2)

In [121]:
x

array([[ 1.,  0.],
       [ 0.,  1.]])

In [124]:
b = np.arange(4).reshape(2,2)

In [125]:
b

array([[0, 1],
       [2, 3]])

In [126]:
a

array([[ 1.,  0.],
       [ 0.,  1.]])

In [127]:
b

array([[0, 1],
       [2, 3]])

In [128]:
a*b

array([[ 0.,  0.],
       [ 0.,  3.]])

In [129]:
x = np.dot(a,b)

In [130]:
x

array([[ 0.,  1.],
       [ 2.,  3.]])

In [131]:
a = np.arange(4)

In [132]:
a

array([0, 1, 2, 3])

In [133]:
a>3

array([False, False, False, False], dtype=bool)

In [134]:
a>2

array([False, False, False,  True], dtype=bool)

In [135]:
10 * np.sin(a)

array([ 0.        ,  8.41470985,  9.09297427,  1.41120008])

In [136]:
x = np.random.random((4,5))

In [137]:
x

array([[ 0.9518203 ,  0.14453273,  0.30930434,  0.990212  ,  0.16983324],
       [ 0.68034415,  0.27916714,  0.13270653,  0.28552012,  0.23062332],
       [ 0.32910833,  0.90950755,  0.98017936,  0.05911245,  0.46981123],
       [ 0.2736223 ,  0.84877022,  0.12710743,  0.2030601 ,  0.85993693]])

In [138]:
x.sum()

9.2342797592425221

In [139]:
x.min()

0.059112454882817356

In [140]:
x.max()

0.99021199523799885

In [143]:
x.min(axis=1)

array([ 0.14453273,  0.13270653,  0.05911245,  0.12710743])

In [144]:
x.min(axis=0)

array([ 0.2736223 ,  0.14453273,  0.12710743,  0.05911245,  0.16983324])

In [145]:
x

array([[ 0.9518203 ,  0.14453273,  0.30930434,  0.990212  ,  0.16983324],
       [ 0.68034415,  0.27916714,  0.13270653,  0.28552012,  0.23062332],
       [ 0.32910833,  0.90950755,  0.98017936,  0.05911245,  0.46981123],
       [ 0.2736223 ,  0.84877022,  0.12710743,  0.2030601 ,  0.85993693]])

In [146]:
x

array([[ 0.9518203 ,  0.14453273,  0.30930434,  0.990212  ,  0.16983324],
       [ 0.68034415,  0.27916714,  0.13270653,  0.28552012,  0.23062332],
       [ 0.32910833,  0.90950755,  0.98017936,  0.05911245,  0.46981123],
       [ 0.2736223 ,  0.84877022,  0.12710743,  0.2030601 ,  0.85993693]])

In [149]:
x = x.ravel()

In [151]:
x.shape

(20,)

In [153]:
x.shape=(4,5)

In [154]:
x

array([[ 0.9518203 ,  0.14453273,  0.30930434,  0.990212  ,  0.16983324],
       [ 0.68034415,  0.27916714,  0.13270653,  0.28552012,  0.23062332],
       [ 0.32910833,  0.90950755,  0.98017936,  0.05911245,  0.46981123],
       [ 0.2736223 ,  0.84877022,  0.12710743,  0.2030601 ,  0.85993693]])

In [155]:
x.transpose()

array([[ 0.9518203 ,  0.68034415,  0.32910833,  0.2736223 ],
       [ 0.14453273,  0.27916714,  0.90950755,  0.84877022],
       [ 0.30930434,  0.13270653,  0.98017936,  0.12710743],
       [ 0.990212  ,  0.28552012,  0.05911245,  0.2030601 ],
       [ 0.16983324,  0.23062332,  0.46981123,  0.85993693]])